version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/app
hooks:
  ApplicationStart:
    - location: start_service.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: stop_service.sh
      timeout: 120
      runas: root
